In [3]:

import numpy as np
import math
import matplotlib.pyplot as plt
from openpyxl import load_workbook
import pandas as pd
from scipy.stats import logistic
#%matplotlib inline
plt.rcParams['figure.figsize'] = [9, 6]



In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(X):
    return np.maximum(0,X)

def relud(X):
    return np.maximum(0,np.sign(X))



In [5]:
#   DADOS TREINO (EXEMPLO)
X = [[23,12, 2,31,22,16,26,16,30,32], # temperatura e vento
    [ 5, 20, 2,31, 2, 4, 4,20,20,30]]
Y = [[ 1, 0, 0, 0, 1, 0, 1, 0, 1, 0]] # ir à praia
X=np.array(X)
print(np.shape(X))
Y=np.array(Y)
np.shape(Y)


# DADOS TREINO





(2, 10)


(1, 10)

In [6]:
##                   UM NEURONIO 


#   COEFICIENTES NEURONIO
W=[0.5,0.5]             #2 FEATURES, 1 NEURONIO
W=np.array(W)
W=np.reshape(W,(2,1))
np.shape(W)
b=1



In [7]:
for i in range(10000):
    #   ESTIMADOR LINEAR
    Z=np.dot(W.T,X)+b

    #   CLASSIFICAÇÃO BINÁRIA (PROBABLIDADE)
    A=logistic.cdf(Z)


    #   ERROS (#diferenças para o real)
    dZ = A - Y

    # 10 elementos no conjunto de treino, derivadas nos coeficientes para otimizar
    dW=1/10*np.dot(X,dZ.T)  ## 10 = len(X[1])

    db=1/10*np.sum(dZ)

    lr=0.002 #learning rate

    #   COEFICIENTES ATUALIZADOS
    W=W-lr*dW
    b=b-lr*db

print('Coef. Rede de 1 Neuronio', (W,b))
print('Erros', dZ)


Coef. Rede de 1 Neuronio (array([[ 0.18199801],
       [-0.24146526]]), -0.7093268402733357)
Erros [[-0.09369717  0.03374563  0.30403809  0.07223672 -0.05669487  0.77501053
  -0.04492707  0.06744558 -0.51966804  0.10627468]]


In [8]:
# Exemplo de uso
print('-')
X=[35,0] #35 graus, 0m/s de vento
Z=np.dot(W.T,X)+b
print(Z)
A=logistic.cdf(Z)
print(A)


-
[5.6606035]
[0.99653166]


In [9]:

print('-')
print('3 Neuronios')
#           3 NEURONIOS

def tres_neuronios(X, Y,
                   W1, b1, #COEF NEURONIOS
                   W2, b2,
                   iteracoes=10000,
                   max_error=False,
                   erro_maximo = 10**-6,
                   var_uso = False,
                   dados_uso = []):

    erro = False

    for i in range(iteracoes):

        Z1=np.dot(W1,X)+b1
        
        A1=relu(Z1)

        Z2=np.dot(W2,A1)+b2

        A2=logistic.cdf(Z2)

        dZ2=A2-Y

        dW2=1/10*np.dot(dZ2,A1.T)

        np.shape(dW2)
        db2=1/10*np.sum(dZ2)

        dZ1=np.multiply(np.dot(W2.T,dZ2),(relud(Z1)))

        np.shape(dZ1)
        dW1=1/10*np.dot(dZ1,X.T)

        np.shape(dW1)
        db1=1/10*np.sum(dZ1)

        lr=0.003 #learning rate
        W1=W1-lr*dW1
        b1=b1-lr*db1
        W2=W2-lr*dW2
        b2=b2-lr*db2

        ## Media erros
        media_erros = np.mean(dZ2)

        if max_error == True:
            if abs(media_erros) < erro_maximo:
                erro = True
                break

    if erro == True and max_error == True:
        print('Obtemos, em média, erros menor a ', erro_maximo)
    elif erro == False and max_error == True:
        print('Não foram iterações suf. para ter erro menor ao maximo')

    print(W1, b1)
    print(W2, b2)
    print('Errors', dZ2)


    #USO
    if var_uso == True:
        Z=np.dot(W.T,dados_uso)+b
        A=logistic.cdf(Z)

        return print('Prob.', A)

    return dZ2

-
3 Neuronios


In [10]:

#DADOS TESTES

X = [[23, 12, 2,31,22,16,26,16,30,32,27,28,24,20,18,28], # temperatura e vento
    [ 5, 20, 2,31, 2, 4, 4,20,20,30, 5,10, 2,15, 4,18]]
X=np.array(X)
Y=[[ 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0]] # ir à praia
Y=np.array(Y)


#   COEF. NEURONIOS
W1=[[0.5,-0.5],[0.02,0.01],[-0.1,-0.2]] #2 FEATURES, 3 NEURONIOS
W1=np.reshape(W1,(3,2))  

b1=[0.2,0.1,-0.1]
b1=np.reshape(b1,(3,1))

W2=[0.01,0.02,0.03]      #3 FEATURES, 1 NEURONIO (final)
W2=np.reshape(W2,(1,3))

b2=0.1

print('Exemplo uso, sem erro maximo')
dados_uso =[35,0]
tres_neuronios(X,Y, W1, b1, W2, b2)
               #var_uso = True, dados_uso = dados_uso)

Exemplo uso, sem erro maximo
[[ 0.89731826 -0.37674247]
 [-0.04380223  0.20267619]
 [-0.1        -0.2       ]] [[0.74885487]
 [0.64885487]
 [0.44885487]]
[[ 0.22560362 -0.85921667  0.03      ]] -2.2810205508551857
Errors [[-0.17482052  0.00686841  0.06250836  0.03671693 -0.11012916  0.53293346
  -0.07374135  0.0177325  -0.65843624  0.05907289 -0.07506931 -0.18916776
  -0.07115009  0.14688408  0.64831889  0.35028932]]


array([[-0.17482052,  0.00686841,  0.06250836,  0.03671693, -0.11012916,
         0.53293346, -0.07374135,  0.0177325 , -0.65843624,  0.05907289,
        -0.07506931, -0.18916776, -0.07115009,  0.14688408,  0.64831889,
         0.35028932]])

In [11]:
df_diabetes = pd.read_csv('dados_treino_diabetes.csv',
                          usecols=[0,1,2,3,5,6,7,8])


df_diabetes.head(10)

gender   age  hypertension  heart_disease    bmi  HbA1c_level  \
0  Female  80.0             0              1  25.19          6.6   
1  Female  54.0             0              0  27.32          6.6   
2    Male  28.0             0              0  27.32          5.7   
3  Female  36.0             0              0  23.45          5.0   
4    Male  76.0             1              1  20.14          4.8   
5  Female  20.0             0              0  27.32          6.6   
6  Female  44.0             0              0  19.31          6.5   
7  Female  79.0             0              0  23.86          5.7   
8    Male  42.0             0              0  33.64          4.8   
9  Female  32.0             0              0  27.32          5.0   

   blood_glucose_level  diabetes  
0                  140         0  
1                   80         0  
2                  158         0  
3                  155         0  
4                  155         0  
5                   85         0  
6                  200         1  
7                   85         0  
8                  145         0  
9                  100         0

In [12]:
genero = []
for i in df_diabetes['gender'].values:
    if i == 'Male':
        genero.append(0)
    else:
        genero.append(1)

del df_diabetes['gender']


In [13]:
df_diabetes.insert(loc=0, column='gender', value=genero)

df_diabetes




gender   age  hypertension  heart_disease    bmi  HbA1c_level  \
0           1  80.0             0              1  25.19          6.6   
1           1  54.0             0              0  27.32          6.6   
2           0  28.0             0              0  27.32          5.7   
3           1  36.0             0              0  23.45          5.0   
4           0  76.0             1              1  20.14          4.8   
...       ...   ...           ...            ...    ...          ...   
99995       1  80.0             0              0  27.32          6.2   
99996       1   2.0             0              0  17.37          6.5   
99997       0  66.0             0              0  27.83          5.7   
99998       1  24.0             0              0  35.42          4.0   
99999       1  57.0             0              0  22.43          6.6   

       blood_glucose_level  diabetes  
0                      140         0  
1                       80         0  
2                      158         0  
3                      155         0  
4                      155         0  
...                    ...       ...  
99995                   90         0  
99996                  100         0  
99997                  155         0  
99998                  100         0  
99999                   90         0  

[100000 rows x 8 columns]

In [14]:
## Testes
df_diabetes = df_diabetes[:1000]
df_diabetes

gender   age  hypertension  heart_disease    bmi  HbA1c_level  \
0         1  80.0             0              1  25.19          6.6   
1         1  54.0             0              0  27.32          6.6   
2         0  28.0             0              0  27.32          5.7   
3         1  36.0             0              0  23.45          5.0   
4         0  76.0             1              1  20.14          4.8   
..      ...   ...           ...            ...    ...          ...   
995       0  62.0             0              0  29.26          5.0   
996       1  44.0             0              0  46.07          5.0   
997       0  21.0             0              0  31.44          6.2   
998       0  45.0             0              1  38.25          6.1   
999       1  43.0             0              0  27.32          6.6   

     blood_glucose_level  diabetes  
0                    140         0  
1                     80         0  
2                    158         0  
3                    155         0  
4                    155         0  
..                   ...       ...  
995                  200         0  
996                  145         0  
997                   85         0  
998                  140         0  
999                  130         1  

[1000 rows x 8 columns]

In [15]:
### DADOS TREINO DIABETES

X = [df_diabetes['gender'], df_diabetes['age'], df_diabetes['hypertension'], 
     df_diabetes['heart_disease'], df_diabetes['bmi'],
     df_diabetes['HbA1c_level'], df_diabetes['blood_glucose_level']]
X = np.array(X)
print(np.shape(X))


Y = df_diabetes['diabetes']
Y = np.array(Y).T

W1 = np.zeros((3,7))
for i in range(3):
    for j in range(7):
        W1[i][j] = np.random.uniform(-0.1, 0.1)

W2= np.array([np.random.uniform(-0.1, 0.1, 3)])
W2 = np.reshape(W2,(1,3)) 

print(W1)
print(W2)

b1=[0.2,0.1,-0.1]
b1=np.reshape(b1,(3,1))

b2=0.1

        

(7, 1000)
[[ 0.00701492  0.02502724  0.06874372 -0.0902434  -0.07073335 -0.00735687
   0.05835058]
 [-0.02525262 -0.04563463 -0.07444019  0.08441666 -0.0024601  -0.04907965
   0.09400002]
 [-0.07883576  0.03110318 -0.07855328 -0.02713789  0.08997156  0.03077294
   0.00910029]]
[[ 0.00048686 -0.03008875  0.02923349]]


In [16]:
tres_neuronios(X,Y, W1, b1, W2, b2, iteracoes=1000)

[[-4.32499444e-03 -1.14670218e+00  6.53733468e-02 -9.19284556e-02
  -6.99053021e-01 -1.49627444e-01 -3.52876882e+00]
 [-4.03806843e-02 -1.69393217e+00 -7.94084260e-02  8.19245949e-02
  -8.65712187e-01 -2.47071959e-01 -4.91441449e+00]
 [-8.09116046e-02 -1.02658425e-01 -7.87227432e-02 -2.72149094e-02
  -1.30563478e-03  1.24999793e-02 -4.36108105e-01]] [[ 0.15019855]
 [ 0.05019855]
 [-0.14980145]]
[[-0.59385433  1.44346932 -0.53374881]] -2.415478143219006
Errors [[ 0.082  0.082  0.082  0.082  0.082  0.082 -0.918  0.082  0.082  0.082
   0.082  0.082  0.082  0.082  0.082  0.082  0.082  0.082  0.082  0.082
   0.082  0.082  0.082  0.082  0.082  0.082 -0.918  0.082  0.082  0.082
   0.082  0.082  0.082  0.082  0.082  0.082  0.082  0.082 -0.918  0.082
  -0.918  0.082  0.082  0.082  0.082  0.082  0.082  0.082  0.082  0.082
   0.082  0.082  0.082 -0.918  0.082 -0.918  0.082  0.082  0.082 -0.918
   0.082  0.082  0.082  0.082  0.082  0.082  0.082  0.082  0.082  0.082
   0.082  0.082  0.082  0.082  0

array([[ 0.082,  0.082,  0.082,  0.082,  0.082,  0.082, -0.918,  0.082,
         0.082,  0.082,  0.082,  0.082,  0.082,  0.082,  0.082,  0.082,
         0.082,  0.082,  0.082,  0.082,  0.082,  0.082,  0.082,  0.082,
         0.082,  0.082, -0.918,  0.082,  0.082,  0.082,  0.082,  0.082,
         0.082,  0.082,  0.082,  0.082,  0.082,  0.082, -0.918,  0.082,
        -0.918,  0.082,  0.082,  0.082,  0.082,  0.082,  0.082,  0.082,
         0.082,  0.082,  0.082,  0.082,  0.082, -0.918,  0.082, -0.918,
         0.082,  0.082,  0.082, -0.918,  0.082,  0.082,  0.082,  0.082,
         0.082,  0.082,  0.082,  0.082,  0.082,  0.082,  0.082,  0.082,
         0.082,  0.082,  0.082,  0.082,  0.082,  0.082,  0.082,  0.082,
         0.082, -0.918,  0.082,  0.082,  0.082,  0.082,  0.082, -0.918,
         0.082,  0.082,  0.082,  0.082,  0.082,  0.082, -0.918,  0.082,
        -0.918,  0.082,  0.082,  0.082,  0.082,  0.082,  0.082,  0.082,
        -0.918,  0.082,  0.082,  0.082,  0.082,  0.082,  0.082, 

In [27]:



##### TESTES OUTROS DADOS

df_diabetes_2 = pd.read_csv('TESTEpima-indians-diabetes.csv')

df_diabetes_2.head(10)


X2 = [df_diabetes_2['1'], df_diabetes_2['2'], df_diabetes_2['3'], 
     df_diabetes_2['4'], df_diabetes_2['5'],
     df_diabetes_2['6'], df_diabetes_2['7'],
     df_diabetes_2['8']]

X2 = np.array(X2)

Y2 = df_diabetes_2['9']
Y2 = np.array(Y).T


W1_1 = np.zeros((3,8))

for i in range(3):
    for j in range(8):
        W1_1[i][j] = np.random.uniform(-0.1, 0.1)

   
W2_2= np.array([np.random.uniform(-0.1, 0.1, 3)])
W2_2 = np.reshape(W2_2,(1,3)) 

b1=[0.2,0.1,-0.1]
b1=np.reshape(b1,(3,1))

b2=0.1


### Usar dados para prevermos depois o resultado

FileNotFoundError: [Errno 2] No such file or directory: 'TESTEpima-indians-diabetes.csv'

In [17]:
tres_neuronios(X2,Y2, W1_1, b1, W2_2, b2, iteracoes=100)


NameError: name 'X2' is not defined